### ISSUE TITLE
[Feature Request] Install configuration

### ISSUE THREAD

**Issue by Maxador** [eXolnet/exolnet-macos-toolbox#1]
Il serait intéressant d'avoir un moyen de configurer certains outils pour éviter des conflits.
Par exemple, j'ai installé `macvim`  avec `brew` et je ne peux pas installer `vim`.

J'ai dû modifier le script d'installation pour contourner le problème, mais je dois _commit_ le changement et je ne veux pas le propager à tout le monde par erreur (si je contribue au script).

On pourrait utiliser quelques variables d'environnement pour pouvoir permettre aux gens de personnaliser certaines étapes de l'installation. Si certaines variables sont manquantes, tout le monde peut faire un _feature request_ pour l'ajouter.

**Comment by pgrenaud** [comment]
Devrait maintenant être corrigé avec le script exo-bash-install. Ce script devrait être exécuté une fois lors de l'installation du poste de travail et n'est pas appelé par exo-self-reinstall. Cela ne donne pas la fonctionnalité escomptée, mais résout le problème en ne créant plus de conflit.
